export default [
  {
    architecture: [
      {
        id: 0,
        category: 'residential',
        src: 'arch/munna/munna_1.jpg',
        children: [
          'arch/munna/munna_1.jpg',
          'arch/munna/munna_2.jpg',
          'arch/munna/munna_3.jpg',
          'arch/munna/munna_4.jpg',
        ],
        description: {
          name: 'Curtain wall house',
          client: 'Mr. Nowaiser',
          area: '4,176',
          location: 'Uchila, Mangalore',
        },
      },
      {
        id: 1,
        category: 'residential',
        src: 'arch/sagar/sagar_1.jpg',
        children: [
          'arch/sagar/sagar_1.jpg',
          'arch/sagar/sagar_2.jpg',
          'arch/sagar/sagar_3.jpg',
        ],
        description: {
          name: 'Sagar Residency',
          client: 'Sagar textiles',
          area: '5,850',
          location: 'Ullala,Mangalore',
        },
      },
      {
        id: 2,
        category: 'residential',
        src: 'arch/muzafir/muzafir_1.jpg',
        children: [
          'arch/muzafir/muzafir_1.jpg',
        ],
        description: {
          name: 'Muzzafir residency',
          client: 'Mr. Muzzafir',
          area: '3,700',
          location: 'Nelamangala, Bangalore',
        },
      },
      {
        id: 3,
        category: 'residential',
        src: 'arch/ismail/ismail_1.jpg',
        children: [
          'arch/ismail/ismail_1.jpg',
          'arch/ismail/ismail_2.jpg',
        ],
        description: {
          name: 'Terrace view apartment',
          client: 'Mr. Ismail',
          area: '11,300',
          location: 'Puttur, Mangalore',
        },
      },
      {
        id: 4,
        category: 'residential',
        src: 'arch/poovayya/poovayya_1.jpg',
        children: [
          'arch/poovayya/poovayya_1.jpg',
          'arch/poovayya/poovayya_2.jpg',
          'arch/poovayya/poovayya_3.jpg',
        ],
        description: {
          name: 'Poovayya residency',
          client: 'Mr. Poovayya',
          area: '3,500',
          location: 'Madikery, Kodagu',
        },
      },
      {
        id: 5,
        category: 'commercial',
        src: 'arch/jayanagar/jayanagar_1.jpg',
        children: [
          'arch/jayanagar/jayanagar_1.jpg',
          'arch/jayanagar/jayanagar_2.jpg',
        ],
        description: {
          name: 'Landmark commercial complex',
          client: 'Sanjay  Reddy',
          area: '14,344',
          location: 'Jayanagara, Bangalore',
        },
      },
      {
        id: 6,
        category: 'commercial',
        src: 'arch/banashankari/PINNACLE_1.jpg',
        children: [
          'arch/banashankari/PINNACLE_1.jpg',
          'arch/banashankari/PINNACLE_2.jpg',
        ],
        description: {
          name: 'Pinnacle tower',
          client: 'Pinnacle Globe',
          area: '21,200',
          location: 'Banashankari, Bangalore',
        },
      },
    ],
    interior: [
      {
        id: 0,
        category: 'residential',
        src: 'interior/residence/gopal/1.jpg',
        children: [
          'interior/residence/gopal/1.jpg',
          'interior/residence/gopal/2.jpg',
          'interior/residence/gopal/3.jpg',
          'interior/residence/gopal/4.jpg',
          'interior/residence/gopal/5.jpg',
          'interior/residence/gopal/6.jpg',
          'interior/residence/gopal/7.jpg',
          'interior/residence/gopal/8.jpg',
          'interior/residence/gopal/9.jpg',
          'interior/residence/gopal/10.jpg',
          'interior/residence/gopal/11.jpg',
          'interior/residence/gopal/12.jpg',
          'interior/residence/gopal/13.jpg',
        ],
        description: {
          client: 'Mr. Gopal',
          location: 'Bangalore',
        },
      },
      {
        id: 1,
        category: 'residential',
        src: 'interior/residence/jayaprakash/1.jpg',
        children: [
          'interior/residence/jayaprakash/1.jpg',
          'interior/residence/jayaprakash/2.jpg',
          'interior/residence/jayaprakash/3.jpg',
          'interior/residence/jayaprakash/4.jpg',
          'interior/residence/jayaprakash/5.jpg',
          'interior/residence/jayaprakash/6.jpg',
          'interior/residence/jayaprakash/7.jpg',
          'interior/residence/jayaprakash/8.jpg',
          'interior/residence/jayaprakash/9.jpg',
          'interior/residence/jayaprakash/10.jpg',
          'interior/residence/jayaprakash/11.jpg',
          'interior/residence/jayaprakash/12.jpg',
          'interior/residence/jayaprakash/13.jpg',
          'interior/residence/jayaprakash/14.jpg',
        ],
        description: {
          client: 'Mr. Jayaprakash',
          location: 'Erode, Tamilnadu',
        },
      },
      {
        id: 2,
        category: 'residential',
        src: 'interior/residence/riyaz/1.jpg',
        children: [
          'interior/residence/riyaz/1.jpg',
          'interior/residence/riyaz/2.jpg',
          'interior/residence/riyaz/3.jpg',
          'interior/residence/riyaz/4.jpg',
          'interior/residence/riyaz/5.jpg',
          'interior/residence/riyaz/6.jpg',
          'interior/residence/riyaz/7.jpg',
          'interior/residence/riyaz/8.jpg',
          'interior/residence/riyaz/9.jpg',
          'interior/residence/riyaz/10.jpg',
          'interior/residence/riyaz/11.jpg',
          'interior/residence/riyaz/12.jpg',
        ],
        description: {
          client: 'Mr. Riyaz',
          location: 'Mangalore',
        },
      },
      {
        id: 3,
        category: 'residential',
        src: 'interior/residence/tumkur/1.jpg',
        children: [
          'interior/residence/tumkur/1.jpg',
          'interior/residence/tumkur/2.jpg',
          'interior/residence/tumkur/3.jpg',
          'interior/residence/tumkur/4.jpg',
          'interior/residence/tumkur/5.jpg',
          'interior/residence/tumkur/6.jpg',
          'interior/residence/tumkur/7.jpg',
          'interior/residence/tumkur/8.jpg',
          'interior/residence/tumkur/9.jpg',
          'interior/residence/tumkur/10.jpg',
          'interior/residence/tumkur/11.jpg',
          'interior/residence/tumkur/12.jpg',
          'interior/residence/tumkur/13.jpg',
        ],
        description: {
          client: 'Prof. Keshav',
          location: 'Tumkur',
        },
      },
      {
        id: 4,
        category: 'corporate',
        src: 'interior/corporate/mnc_office/1.jpg',
        children: [
          'interior/corporate/mnc_office/1.jpg',
          'interior/corporate/mnc_office/2.jpg',
          'interior/corporate/mnc_office/3.jpg',
          'interior/corporate/mnc_office/4.jpg',
          'interior/corporate/mnc_office/5.jpg',
          'interior/corporate/mnc_office/6.jpg',
          'interior/corporate/mnc_office/7.jpg',
          'interior/corporate/mnc_office/8.jpg',
          'interior/corporate/mnc_office/9.jpg',
          'interior/corporate/mnc_office/10.jpg',
        ],
        description: {
          client: 'Mr. Madukar',
          location: 'Mysore',
        },
      },
      {
        id: 5,
        category: 'corporate',
        src: 'interior/corporate/office_interior/1.jpg',
        children: [
          'interior/corporate/office_interior/1.jpg',
          'interior/corporate/office_interior/2.jpg',
          'interior/corporate/office_interior/3.jpg',
          'interior/corporate/office_interior/4.jpg',
          'interior/corporate/office_interior/5.jpg',
          'interior/corporate/office_interior/6.jpg',
          'interior/corporate/office_interior/7.jpg',
          'interior/corporate/office_interior/8.jpg',
          'interior/corporate/office_interior/9.jpg',
          'interior/corporate/office_interior/10.jpg',
          'interior/corporate/office_interior/11.jpg',
        ],
        description: {
          client: 'Mr. Sharafath',
          location: 'Bangalore',
        },
      },
    ],
  },
];
